language: r
sudo: required

# Packages from Bioconductor needed
bioc_required: true

env:
  global:
    - BIOC_USE_DEVEL="TRUE"

# Package dependencies installed using apt-get
apt_packages:
  - gsl-bin
  - libgsl0-dev

# Be strict when checking package
warnings_are_errors: true

# Package dependencies from CRAN
r_binary_packages:
  - RUnit
  - Rcpp
  - knitr
  - rmarkdown
  - MCMCpack

# Package dependencies from Bioconductor
bioc_packages:
  - BiocGenerics
  - GenomeInfoDb
  - IRanges
  - BiocStyle
  - GenomicRanges
  - nucleoSim
  - consensusSeekeR
  - PING

# Package dependencies from github
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'Rcpp::compileAttributes(); library(covr);codecov()'
