language: r
sudo: required

# Packages from Bioconductor needed
bioc_required: true

env:
  global:
    - BIOC_USE_DEVEL="TRUE"

#before_install:
#  - sudo apt-get -qq update

# Package dependencies installed using apt-get
apt_packages:
  - gsl-bin
  - libgsl0-dev
  - libgsl0ldbl
  - r-bioc-biocgenerics

# Be strict when checking package
warnings_are_errors: false

# Package dependencies from CRAN
r_binary_packages:
  - RUnit
  - Rcpp
  - knitr
  - rmarkdown
  - covr

# Package dependencies from Bioconductor
bioc_packages:
  - GenomeInfoDb
  - IRanges
  - BiocStyle
  - GenomicRanges
  - nucleoSim
  - consensusSeekeR
  - PING
# - BiocGenerics

# Package dependencies from github
r_github_packages:
  - jimhester/covr

before_script:
  - Rscript -e 'library(Rcpp); Rcpp::compileAttributes()'

after_success:
  - Rscript -e 'library(covr); codecov()'
