language: r
sudo: required

cache: packages

# Packages from Bioconductor needed
bioc_required: true

# Be strict when checking package
warnings_are_errors: false

# Set variables
env:
  global:
    - BIOC_USE_DEVEL="TRUE"

# Package dependencies installed using apt-get
apt_packages:
  - gsl-bin
  - libgsl0-dev
  - libgsl0ldbl

# Package dependencies from CRAN
r_binary_packages:
  - RUnit
  - Rcpp
  - knitr
  - rmarkdown
  - covr

# Package dependencies from Bioconductor
bioc_packages:
   - BiocGenerics
   - GenomeInfoDb
   - IRanges
   - BiocStyle
   - GenomicRanges
   - nucleoSim
   - consensusSeekeR
   - PING

# Package dependencies from github
#r_github_packages:
#  - jimhester/covr

before_script:
  - Rscript -e 'library(Rcpp); Rcpp::compileAttributes()'

after_success:
  - Rscript -e 'library(covr); codecov()'
