language: r
sudo: required

# R version
r: bioc-release

# Package caching only makes sense for the release versions.
cache: packages

# Packages from Bioconductor needed
bioc_required: true

# Be strict when checking package
warnings_are_errors: false

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

# Package dependencies installed using apt-get
apt_packages:
  - gsl-bin
  - libgsl0-dev
  - libgsl0ldbl

# Package dependencies from CRAN
r_binary_packages:
   - covr
#  - RUnit
#  - Rcpp
#  - knitr
#  - rmarkdown


# To compile C++ code
before_script:
  - Rscript -e 'library(Rcpp); Rcpp::compileAttributes()'

# To send info to codecov
after_success:
  - Rscript -e 'library(covr); codecov()'
